blank_issues_enabled: false
contact_links:
  - name: Propose a feature
    url: https://github.com/DavLagoHern/LakeDB/discussions/categories/ideas
    about: Share an idea, explain the use case and let the community vote.
  - name: Ask a question
    url: https://github.com/DavLagoHern/LakeDB/discussions/categories/q-a
    about: Get help using LakeDB or help another user.
  - name: Read the Wiki
    url: https://github.com/DavLagoHern/LakeDB/wiki
    about: Browse guides, FAQs and known solutions.
